ALTER TABLE GatedLinks ADD COLUMN IF NOT EXISTS description TEXT NULL;
ALTER TABLE GatedLinks ADD COLUMN IF NOT EXISTS author_name TEXT NULL;
ALTER TABLE GatedLinks ADD COLUMN IF NOT EXISTS author_profile_picture_url TEXT NULL;
ALTER TABLE GatedLinks ADD COLUMN IF NOT EXISTS content_vignette_url TEXT NULL;
ALTER TABLE GatedLinks ADD COLUMN IF NOT EXISTS publication_date TIMESTAMPTZ NULL;
ALTER TABLE GatedLinks ADD COLUMN IF NOT EXISTS extracted_metadata JSONB NULL; 